# Generated by Django 4.2 on 2023-05-27 17:23

from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', validators=[shop.validators.validate_image_size])),
            ],
        ),
    ]
