# Generated by Django 4.2 on 2023-06-19 14:25

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='shop/images', validators=[shop.validators.validate_image_size]),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
